### ISSUE TITLE
discovery not working 

### ISSUE THREAD

**Issue by clock157** [pires/docker-elasticsearch-aws#3]
hi,pires.
when i run client or data,it's cant discovery and show these errors.

```
addgroup: group 'sudo' in use
adduser: user 'elasticsearch' in use
[2016-09-13 12:38:49,240][INFO ][node                     ] [Lorvex] version[2.3.5], pid[11], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-13 12:38:49,241][INFO ][node                     ] [Lorvex] initializing ...
[2016-09-13 12:38:50,600][INFO ][plugins                  ] [Lorvex] modules [reindex, lang-expression, lang-groovy], plugins [cloud-aws, analysis-ik], sites []
[2016-09-13 12:38:52,949][INFO ][ik-analyzer              ] try load config from /elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml
[2016-09-13 12:38:53,663][INFO ][ik-analyzer              ] [Dict Loading] custom/mydict.dic
[2016-09-13 12:38:53,663][INFO ][ik-analyzer              ] [Dict Loading] custom/single_word_low_freq.dic
[2016-09-13 12:38:53,672][INFO ][ik-analyzer              ] [Dict Loading] custom/ext_stopword.dic
[2016-09-13 12:38:54,749][INFO ][node                     ] [Lorvex] initialized
[2016-09-13 12:38:54,751][INFO ][node                     ] [Lorvex] starting ...
[2016-09-13 12:38:54,895][INFO ][transport                ] [Lorvex] publish_address {10.20.22.15:9300}, bound_addresses {10.20.22.15:9300}
[2016-09-13 12:38:54,912][INFO ][discovery                ] [Lorvex] unicall-es/4YV18Dm6RFWk4UVPZOOGkg
[2016-09-13 12:38:54,958][WARN ][com.amazonaws.jmx.SdkMBeanRegistrySupport]
java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "findMBeanServer")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
    at java.security.AccessController.checkPermission(AccessController.java:884)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    at javax.management.MBeanServerFactory.checkPermission(MBeanServerFactory.java:413)
    at javax.management.MBeanServerFactory.findMBeanServer(MBeanServerFactory.java:361)
    at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:111)
    at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:50)
    at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
    at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:355)
    at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:316)
    at com.amazonaws.AmazonWebServiceClient.requestMetricCollector(AmazonWebServiceClient.java:563)
    at com.amazonaws.AmazonWebServiceClient.isRMCEnabledAtClientOrSdkLevel(AmazonWebServiceClient.java:504)
    at com.amazonaws.AmazonWebServiceClient.isRequestMetricsEnabled(AmazonWebServiceClient.java:496)
    at com.amazonaws.AmazonWebServiceClient.createExecutionContext(AmazonWebServiceClient.java:457)
    at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5924)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.fetchDynamicNodes(AwsEc2UnicastHostsProvider.java:118)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:230)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:215)
    at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.buildDynamicNodes(AwsEc2UnicastHostsProvider.java:104)
    at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:335)
    at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:240)
    at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:106)
    at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:84)
    at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:886)
    at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:350)
    at org.elasticsearch.discovery.zen.ZenDiscovery.access$4800(ZenDiscovery.java:91)
    at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[2016-09-13 12:38:54,965][WARN ][com.amazonaws.metrics.AwsSdkMetrics]
java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "findMBeanServer")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
    at java.security.AccessController.checkPermission(AccessController.java:884)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    at javax.management.MBeanServerFactory.checkPermission(MBeanServerFactory.java:413)
    at javax.management.MBeanServerFactory.findMBeanServer(MBeanServerFactory.java:361)
    at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:111)
    at com.amazonaws.jmx.MBeans.isRegistered(MBeans.java:98)
    at com.amazonaws.jmx.SdkMBeanRegistrySupport.isMBeanRegistered(SdkMBeanRegistrySupport.java:46)
    at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:361)
    at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:316)
    at com.amazonaws.AmazonWebServiceClient.requestMetricCollector(AmazonWebServiceClient.java:563)
    at com.amazonaws.AmazonWebServiceClient.isRMCEnabledAtClientOrSdkLevel(AmazonWebServiceClient.java:504)
    at com.amazonaws.AmazonWebServiceClient.isRequestMetricsEnabled(AmazonWebServiceClient.java:496)
    at com.amazonaws.AmazonWebServiceClient.createExecutionContext(AmazonWebServiceClient.java:457)
    at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5924)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.fetchDynamicNodes(AwsEc2UnicastHostsProvider.java:118)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:230)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:215)
    at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
    at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.buildDynamicNodes(AwsEc2UnicastHostsProvider.java:104)
    at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:335)
    at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:240)
    at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:106)
    at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:84)
    at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:886)
    at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:350)
    at org.elasticsearch.discovery.zen.ZenDiscovery.access$4800(ZenDiscovery.java:91)
    at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)



[2016-09-13 12:39:24,918][WARN ][discovery                ] [Lorvex] waited for 30s and no initial state was set by the discovery
[2016-09-13 12:39:24,926][INFO ][http                     ] [Lorvex] publish_address {10.20.22.15:9200}, bound_addresses {10.20.22.15:9200}
[2016-09-13 12:39:24,927][INFO ][node                     ] [Lorvex] started
```

**Comment by pires** [comment]
This is a problem with AWS discovery plug-in. Can you please report upstream and link this issue?

**Comment by clock157** [comment]
i have make some change of elasticsearch.yml, 
add region and change tag to groups.

```
cloud:
  aws:
    region: ${REGION}
    access_key: ${AWS_KEY}
    secret_key: ${AWS_SECRET}

discovery:
  type: ec2
  ec2.groups: ${GROUP_NAME}
  zen:
    minimum_master_nodes: ${NUMBER_OF_MASTERS}
```

then docker run like this,it works!

```
#Master
docker run --name elasticsearch-master \
    --detach \
    --privileged \
    --volume /data/elasticsearch:/data \
    -p 9300:9300 \
    -e CLUSTER_NAME=my-es \
    -e ES_HEAP_SIZE=256m \
    -e NODE_DATA=false \
    -e HTTP_ENABLE=false \
    -e AWS_KEY=*key* \
    -e AWS_SECRET=*secret* \
    -e GROUP_NAME=v2-tst-host1-sg \
    my_registry/elasticsearch:0.1.3
#client
docker run --name elasticsearch-client \
    --detach \
    --privileged \
    --volume /data/elasticsearch:/data \
    -p 9200:9200 \
    -e CLUSTER_NAME=my-es \
    -e ES_HEAP_SIZE=256m \
    -e NODE_MASTER=false \
    -e NODE_DATA=false \
    -e AWS_KEY=*key* \
    -e AWS_SECRET=*secret* \
    -e GROUP_NAME=v2-tst-host1-sg \
    my_registry/elasticsearch:0.1.3
#data
docker run --name elasticsearch-data \
    --detach \
    --privileged \
    --volume /data/elasticsearch:/data \
    -e CLUSTER_NAME=my-es \
    -e ES_HEAP_SIZE=1024m \
    -e NODE_MASTER=false \
    -e HTTP_ENABLE=false \
    -e AWS_KEY=*key* \
    -e AWS_SECRET=*secret* \
    -e GROUP_NAME=v2-tst-host1-sg \
    my_registry/elasticsearch:0.1.3
```

**Comment by pires** [comment]
So you're using tour own images.
